image: gradle:7.3.1-jdk17-alpine

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd GoMeals/backend
    - echo "Starting build stage . . ."
    - cat /etc/os-release
    - chmod +x ./GoMeals/backend/gradlew
    - ./GoMeals/backend/gradlew build
    - java -version
    - echo "Build complete!"